kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zeppelin-notebooks
  namespace: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
