apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeppelin
  namespace: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: projectepic/zeppelin-cassandra:1.0.6
          env:
            - name: ZEPPELIN_PORT
              value: "8080"
            - name: ZEPPELIN_SERVER_CONTEXT_PATH
              value: "/zeppelin/"
            - name: MASTER
              value: spark://spark-master:7077
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /zeppelin/
              port: 8080
          resources:
            requests:
              cpu: 100m
              memory: 1.5Gi
            limits:
              cpu: 100m
              memory: 1.5Gi
          volumeMounts:
            - name: datadir
              mountPath: /opt/zeppelin/notebook/
      volumes:
      #- name: conf
      #  emptyDir: {}
        - name: datadir
          persistentVolumeClaim:
            claimName: zeppelin-notebooks
