kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: eventmanager-db
  namespace: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
